### PR TITLE
add tsit54 to ode integrators

### PR DESCRIPTION
**Pull request by BarrOff**
Hello and thank you for your great work creating this library!

I implemented Tsitouras 5th order method and added it to the list of integrators.
Informations about the method can be found at [Runge–Kutta pairs of order 5(4) satisfying only the first column simplifying assumption](https://dx.doi.org/10.1016/j.camwa.2011.06.002).

In the testsuite it becomes quiet slow for lower tolerances ( till 1e-7) and fails for <=1e-8.
For higher tolerances it works fine. However, using standard tolerances, it still passes the high tolerance test

Maybe I have missed something there? It would be great if you could take a look at it and help me fix it.

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
Awesome!! 😄 And thank you! It's great that you are contributing 😃 I really appreciate it 😄  

I tried implementing Tsit5 as well but I ran into the same problems as you did so there certainly is something going on :/ Do you know of any other implementations of this algorithm that does not have these issues?

**Comment by HugoGranstrom** [comment]
It is also great that you have written your code in the same way as the already existing code, kudos to you 😉 It's easier said than done 👍

**Comment by BarrOff** [comment]
I looked at the implementation in [Julias DifferentialEquations](https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/tableaus/low_order_rk_tableaus.jl) which I have used successfully in the past. However I could not spot why it works there but not here yet

**Comment by HugoGranstrom** [comment]
Yeah they usually know what they are doing. The most probable reason then, is that the big function that does the processing between steps is doing something wrong. But it's odd that it only happens with Tsit5 and not the others.

**Comment by BarrOff** [comment]
I will take a look at it.

**Comment by HugoGranstrom** [comment]
If I try to use the `ODEoption` that all the others use in the test suite, it seems as if it gets stuck somewhere. So I'm checking how many steps they are taking and with what `dt` and which error they think they are having:
- DOPRI54: `Total steps: 2010 Average dt: 0.009950248756219235 Average error: 1.104699526990206e-018` (for both tests)
- TSIT5 default: `Total steps: 39824 Average dt: 0.0005022097227802303 Average error: 5.901974656708697e-005`
- TSIT5 with `oo`: `Total steps: 398042708 Average dt: 5.024586457188617e-008 Average error: 5.904900054415388e-009`

**Comment by HugoGranstrom** [comment]
If I increase the `minDt` to `1e-6` instead of `1e-8` I get: `Total steps: 39817 Average dt: 0.000502298013411362 Average error: 5.903012249259565e-005` but it passes the test. I would argue that the error control is a bit off, Tsit5 thinks it's much worse than it really is

**Comment by HugoGranstrom** [comment]
I raise `minDt` even higher to `1e-4` and the highest actual error we get is `1e-14` so you have definitely not done anything wrong in you implementation 😉 😄

**Comment by BarrOff** [comment]
Does this fix the problems with Tsit5?

**Comment by HugoGranstrom** [comment]
I hope it does 😊 I will do some further testing tomorrow, but then I don't see any reason not to merge it 😄

**Comment by BarrOff** [comment]
Found a little typo in the documentation comments.
Also tried decreasing dtMin, which seems to fix tsit54. Only the low tolerance vector test takes a little long, but still way faster than before. Tsit54 now uses the same options as all the other methods

**Comment by HugoGranstrom** [comment]
Great, good spotting! 😊👍 Thank you very much! You easily get blind to your own writing 😅 

Do you mind if I ask how you found out NumericalNim? 😄 And have you tried it out and have any general feedback? 😁 Most of my work here is in my own bubble so any outside perspectives are very much appreciated.

**Comment by BarrOff** [comment]
Sure, searching the nimble package registry for a package to solve ODEs this was the only hit, if I remember correctly.

The things I tried so far worked well, so I wanted to contribute. The interfaces arena  intuitive and documentation great which made playing around easy. :grinning:

I would try to implement some higher order methods for low tolerance cases. Inspiration to me is Julia's great DifferentialEquations.jl library. They recommend Vern6, Vern7 or Vern8 for high accuracy, so I'd look further into this?

Also sorry for force pushing my last commits, but I did not want my private mail to be visible in those commits. This won't happen again. :sweat:

**Comment by HugoGranstrom** [comment]
Ah, I see 😄 I'm glad you found it, it's always nice to interact with other likeminded people. Nim is a bit sparse on packages still but I'm sure it will change in a not too distant future. 

It's great to hear that you found the first interaction with NumericalNim to be intuitive 😃 My worst fear is that people come here and can't figure out how to use it 😅 And now you have helped to make it even clearer by fixing my typos 😉👌 What kind of ODE problems are you solving? I'm working on another project which is a gravity simulator so my focus is mainly on solving Newton's equation F = ma. But not using NumericalNim, for better or worse.

JuliaDiffEq is one of my main inspirations as well 😄 It's so huge! The Vern-methods has been on my wishlist for a while so if you feel like you want to and have the time to do it, I would be hugely thankful 🙏 But no hurry at all, take the time you feel that you need 😉😃

I will have to create a Contributions page soon so people like you can get the credit they deserve 🏅 

No worries 😄 I didn't even know what force pushing was prior to yesterday so you made me learn something new 😉

**Comment by BarrOff** [comment]
Yes, I hope Nim will gain some traction now that the stable 1.0.x series is around. Finding nice people with similar interests is great. Exchanging ideas and discussing makes so much fun :blush:

The examples on the front page are really helpful and ease getting started. :+1:

I am working on nonlinear dynamics and chaotic systems for example the Lorentz system. Currently I investigate the effects of noise on neuron models. Those are SDEs. What is your opinion on adding those to numericalnim in the long-term? I would like to try it for the experience of implementing these and to learn about them.

If there are any other rough edges or areas to look at I'll gladly give it a try. :grinning:

**Comment by HugoGranstrom** [comment]
Yes, the 1.0 should really help with making people more willing to give Nim as try 😄 I hope and think we will get along really well 😉 Nice to hear that they are helpful 👍 I've been thinking of doing a more comprehensive tutorial on how you can use all the parts of NumericalNim together in a more concrete way (solving nonlinear ODEs using Newton Raphson for example or loading data from CSV file, interpolate using cubic splines and then integrating it). And one thing I think would be important then is to have real problems to solve, not just the school book examples (sin, cos, exp). If you have any suggestions for any cool problems I would be thrilled to know 😃

Non-linear dynamics and chaos sound really interesting, it's not something I have dabbled with that much in the past but it sounds fascinating 😁 The big question: does noise have an effect on neuron models? 😅 Anything that uses numerical methods is welcome to NumericalNim 😉 If you want to and have the time, I will encourage you to try it out 💯 I have learned so much by implementing the methods that we have right now so I definitely think you will deepen your knowledge on SDEs if you decide to do it. Plus others in the Nim community get to use it 😄 

There are a lot of rough edges everywhere 🤣 But the most valuable help is to just use it and if you come across something that you think would be better done in a different way, just open an issue and let me know 😃 and then we can discuss it

**Comment by HugoGranstrom** [comment]
Regarding Tsit5, I have played around with it a bit today but I can't wrap my head around it really. It is sooooo much slower than the others and is too accurate compared to the others. It should be roughly equivalent to DOPRI5 in performance but they behave so differently. I'm voting for merging this PR but adding a note on the README that it is unstable for now. Hopefully someone can come along and find a way to make it work later. What do you think about that solution? 😄

**Comment by HugoGranstrom** [comment]
I asked on SciComp Stackexchange [here](https://scicomp.stackexchange.com/questions/34395/tsit5-implementation-is-super-slow-and-too-accurate) and got an answer from Chris Rackauckas, one of the guys behind JuliaDiffEq. 

It seems like we (mainly I) have misunderstood what the coefficient was. Those we called `bHat` are not the coefficients for the fourth order methods as in my other integrators but it is the difference between the coefficient of order 5 and 4 so we get the error from: `error = abs(dt * (bHat1 * k1+ bHat2 * k2 + bHat3 * k3 ..........))` and it seems to work! 😄

**Comment by BarrOff** [comment]
Oh, that does explain the strange behaviour. :sweat_smile:

Your suggested fix works for scalars and vectors, but I get an error compiling because the generic abs returns a tensor in case of tensors. With a little change I got it working for me again, I will push it soon. Please take a look at it, maybe this can be done differently or more efficiently.

**Comment by HugoGranstrom** [comment]
Yes, that will do for now 😄 👍 In the future I will try to switch all adaptive ODEs to this form and I think relative errors should be incorporated as well. But that's for another time 😅 

I will do some final checks for this tomorrow and then I'll merge it 😉 same with the Vern65. You were really quick 😲💪

**Comment by HugoGranstrom** [comment]
Great work! :-) Works like a charm now! 😄 I tested Vern65 a bit now and it is FAST 🚀 Will try to resolve the merge conflicts later today

**Pull request merged**
