### PR TITLE
DRY the code for adaptive integrators

### PR DESCRIPTION
**Pull request by BarrOff**
Hello,

I put some common code of the adaptive methods in a template so we don't have to repeat it for every new adaptive method.

Would that be useful or does it make the code more confusing? What is your opinion?
Also, maybe this could be done differently?

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
This is a brilliant idea! 😊✌️👍

**Comment by HugoGranstrom** [comment]
Having to do changes in every proc is quite tedious so this will be really helpful 😉😊 I've found a better formula for the adaptive step size but this makes it a lot less intimidating to implement as I only have to do it in one place. Metaprogamming is so useful when you find ways of using it 😄

**Comment by HugoGranstrom** [comment]
The only way I see this could be improved right now is if we could bake the entire loop into a template and then inject the k1, k2, k3.... code into it. So you would use it something like this replacing the while loop:
```nim
adaptiveOdeTemplate:
    k1 = ....
    k2 = ....
    .
    .
    yNew = ....
    yLow = ....
```

**Comment by BarrOff** [comment]
Yes that would make it even better, but I am not quite sure how to do this, because the number of ks is not fixed. At least I don't see a solution for this right away. Need to think a bit about that a bit.

**Comment by HugoGranstrom** [comment]
I can fix it 😉👍 You can pass blocks of code to a template as well so as long as you name the y:s yNew and yLow then it does really care how you came to those.

**Comment by HugoGranstrom** [comment]
And the code we pass is for example the one in my example. We might have to make the template "dirty" though

**Comment by BarrOff** [comment]
Oh, I see. Reading up on the documentation for templates made it clear. :-)

**Comment by HugoGranstrom** [comment]
Looks good except that we don't pass e1, e2 to it any more. We have to get it from the `body` of code. So we should probably name them e1 and e2 there as well as we don't always want to use yNew and yLow

**Comment by BarrOff** [comment]
Put the whole while loop into the template and added the body. My tests run fine.
The only thing that bugs me with this right now is the placement in the code. Looking at your utils.nim, I saw you putting your template at the bottom of the file but doing so would break ode.nim.
However there is nothing like forward declarations of templates, or am I wrong?

Is there something like a PM or chat option in github? I would like to talk to you about one more thing but that is not directly related to this pull request.

**Comment by HugoGranstrom** [comment]
I don't use the templates in utils.nim in the same file, I only import it in other files so the placement there doesn't matter. You can put this anywhere you like to make it work 😉

**Comment by HugoGranstrom** [comment]
I don't think they have anything like that sadly. You could use Gitter.im or dm me on Twitter

**Comment by HugoGranstrom** [comment]
There's a Nim channel on Gitter which can be interesting to see what happens in the community

**Comment by BarrOff** [comment]
Are you sure it does not work anymore? I get the same results in my test as before ^^

Could you create a channel on gitter then I would join

**Comment by BarrOff** [comment]
Now I see what you mean. What about just moving the error calculation from the template to the body? That should fix it, I guess?

**Comment by HugoGranstrom** [comment]
Just login using your github account and search for hugogranstrom and you should find me 😄
Wasn't the whole point of this PR, not to have to write the error code all the time?😅 If we just decide what the variables should be named, it isn't too hard to just change the names in all the procs and making sure we name them that in the future as well

**Comment by HugoGranstrom** [comment]
I haven't run the code yet, just read it 😅

**Comment by BarrOff** [comment]
Well, point is to remove duplicate code. However the error calculation is just one line (error = calcError(....) ) For example Tsit54 needs other values, so we have no common values

**Comment by HugoGranstrom** [comment]
Sorry, I misunderstood you 😅👍 that is a brilliant idea

**Comment by HugoGranstrom** [comment]
Thought you meant all the code you had in your original commit 🤦‍♀️

**Comment by BarrOff** [comment]
ok, then I will push that soon.

Also, could you please create a gitter channel? Then I could use my matrix account to join and dont have to create yet another account ^^
Why not make an official numericalnim channel? :-)

**Comment by HugoGranstrom** [comment]
Ah I see 😄 I'll try to create one at once

**Comment by HugoGranstrom** [comment]
Join the chat: https://gitter.im/NumericalNim/community

**Comment by HugoGranstrom** [comment]
Your commit looks good 😊✌️ I'll just try it out later and then we could merge it 😉 I'll make sure to merge Vern7 as well.

**Comment by HugoGranstrom** [comment]
Is there anything else I must do so you can join with Matrix? 😄 Any room settings or integration?

**Comment by HugoGranstrom** [comment]
I've added a file for crediting people who contribute to NumericalNim [here](https://github.com/HugoGranstrom/numericalnim/blob/master/Contributions.md)
Feel free to add your additions to it 😉👍

**Comment by BarrOff** [comment]
Can you please add the matrix bot into the room?

Please wait with merging Vern7 till tomorrow , I want to look into it this evening once more. Found a nice page which has implementations of multiple algos: http://www.mymathlib.com/diffeq/

Will look into the file.

**Comment by HugoGranstrom** [comment]
I'm not entierly sure how to do that 😅 I don't have any machine which can act like a bot 24/7 sadly

**Comment by HugoGranstrom** [comment]
Isn't it just easier if you login with your github account and use it? 😅 

The link looks promising although I'm allergic to C code 🤣

**Pull request merged**
