### PR TITLE
Cosmetic fixes

### PR DESCRIPTION
**Pull request by narimiran**
This PR consists of two separate commits: the first one was just reordering stuff around (see edit below) to better respect the line length limits.
(EDIT: Well, now I re-checked and I remembered that in the first commit I also modified some stuff because Nim initializes its variables to their zero value: see for example the changes in `proc trapz` and `proc cumtrapz`)

The second one changes `const gaussWeights` to be an `array` and not a `Table` — see if you're ok with this change. Arrays are usually faster than tables, but in this case it probably won't matter.

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
Thanks 😄 I should probably be running nimpretty or something on this 😅 
Wow, I totally looked passed arrays 🤣 I had `Table`'s O(1) in mind and didn't look at something that obvious. 
 
I will take a look at the code tomorrow and approve it. 😉 
Have tried using NumericalNim? What is your general opinion on it thus far?

**Comment by HugoGranstrom** [comment]
You are right that it shouldn't really make a big difference though 😉 it just gets loaded on time and is neglectable compared to the rest of the logic in the proc. But every optimization is welcome 😁

**Comment by narimiran** [comment]
I've pushed cosmetic changes for other two files too.

> Have tried using NumericalNim?

I haven't had the time yet.
But if only it existed about 1.5–2 years ago, I would have used it in some my PhD-related stuff :) I was doing some comparisons (in Python, IIRC) between various ODE methods, both explicit (including but not limited to RK4 and DOPRI you have here) and implicit (Lobatto, Radau, Gauss-Legendre, etc.). The most from [this list](https://en.wikipedia.org/wiki/List_of_Runge-Kutta_methods) — maybe this gives you some ideas what to implement next :)

> What is your general opinion on it thus far?

I have to have a better look before I can judge and give my opinion :) The changes in this PR are because this is my way of quickly skimming through the code. I would like to dig deeper but I cannot promise when that might happen, due to my lack of time.

**Comment by HugoGranstrom** [comment]
Awesome! 😁

Totally understandable 😄👍 you must be skimming through lots of code 😉 seems like I should try out making a implicit method up next. Thanks for the link and for taking your time 😊 it helps immensely to not develop in a complete vacuum just for my own curiosity. 

I'm also coming from a Python background and Nim was really easy to get started with. It really is a wonderful mix between ease of use and performance.

**Comment by HugoGranstrom** [comment]
All the tests were successful 👍 Thanks once again for your support 😄

**Pull request merged**
